### ISSUE TITLE
Join Zoom Meeting Shortcut Doesn't Work

### ISSUE THREAD

**Issue by mzagaja** [SENTINELITE/StreamDeck-Shortcuts#13]
I am attempting to execute the [Join Zoom Meeting](https://www.macstories.net/stories/introducing-the-2022-automation-april-shortcuts-contest-winners/#best-overall-shortcut) shortcut via this Streamdeck plug-in and it fails every time. I can run the shortcut without issue from Shortcuts and the MacOS Shortcuts menu bar, and when I click the Shortcut in Streamdeck I see an indicator that shortcuts is being triggered in some way, but the action does not seem to occur. I've attached a screenshot of my configuration for reference.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/565647/168152889-042fce93-eeac-413e-9698-a6abbc7ed584.png">

**Comment by SENTINELITE** [comment]
Hey, @mzagaja! Thanks for the image! 

Could you run through [these debugging steps?](https://www.craft.do/s/Illo8qoELLMZqq) This should surface the issue. From what little I can see, it appears to be the backend causing trouble. 

In that document there's also a link to make sure the Entitlements are correctly set, along with some more info on that. 

Let me know!

**Comment by mzagaja** [comment]
I went through and have attached my error log here. Thanks for offering to help!

-Mat
[streamdeck-shortcuts-error.log](https://github.com/SENTINELITE/StreamDeck-Shortcuts/files/8732130/streamdeck-shortcuts-error.log)
t

**Comment by SENTINELITE** [comment]
@mzagaja, Can you try giving it another go? I pushed an update that should've fixed this! 

Let me know!

**Comment by mzagaja** [comment]
This seems to be working now (except when the shortcut itself fails, but that's not due to this). Thank you!

**Comment by SENTINELITE** [comment]
Glad that it's working now, @mzagaja! 

Can you talk a little more about what issue you're seeing? There's still a little 
more language semantics that I need to take care of. If you're seeing this following error, it's likely on my end...

Regardless, thanks for the help & glad it's all *mostly* working! 🎉

<img width="375" alt="Screen Shot 2022-07-01 at 1 52 45 PM" src="https://user-images.githubusercontent.com/44782976/176966607-bdbd3c58-78f8-424b-b065-bc68ccb8eebd.png">
