### ISSUE TITLE
Shortcuts stopped working after latest update

### ISSUE THREAD

**Issue by theonedon** [SENTINELITE/StreamDeck-Shortcuts#17]
None of my shortcuts work anymore.  My shortcuts don't appear in the dropdown.

**Comment by SENTINELITE** [comment]
Hey, @theonedon! 

Sorry for the trouble! This issue was patched & deployed yesterday. Just waiting for Elgato to verify the release!

Again, I apologize for this issue.

**Comment by mikecreates86** [comment]
Any update on the timeline for this fix? And how do plugins get updated when pushed?

**Comment by SENTINELITE** [comment]
Hey, @theonedon & @mikecreates86!

The update has been released. Please restart the StreamDeck software to automatically get the new release.

Mike,
• The App gets compiled into a .sdPlugin file.
• The plugin file gets sent to Elgato's dev team via email.
• The file gets manually checked for malware, etc, & upon passing their tests, it gets released to the StreamDeck App Store.
• In order for new updates to be installed to a user's downloaded plugins, they must restart the software, as the updates are only fetched upon startup of the software.

**Comment by theonedon** [comment]
> 

Thank you!
