### ISSUE TITLE
Error at installation step

### ISSUE THREAD

**Issue by facundobianco** [SENTINELITE/StreamDeck-Shortcuts#23]
Hello, I have a Stream Deck MK1, firmare version 6.5.0 (19904) and when I try to install this plugin I got this error message:

> Requires Stream Deck version 6.4 or newer

Thank you!

**Comment by SENTINELITE** [comment]
Hey, @facundobianco!

Are you on Windows? (The plugin only supports macOS).

Can you provide some more info on your system? Ie. Specs?

**Comment by facundobianco** [comment]
Hi @SENTINELITE!

I'm using MBP 2022 M2 - Sonoma 14.2.1.

**Comment by GeekyEggo** [comment]
Hi @facundobianco, is this the message you’re seeing?
![image](https://github.com/SENTINELITE/StreamDeck-Shortcuts/assets/1429781/e892e875-e145-49c7-b567-e5932448a323)

This is a prompt from Marketplace intended for users with older versions of Stream Deck that aren’t compatible with Marketplace.

If you’re running Stream Deck 6.4 or newer, this message can safely be ignored.

**Comment by facundobianco** [comment]
Finally, the error was resolved: needed to restart app.
It's for Apple but behaves like for MS 😛 

Thank you for your help!
