### ISSUE TITLE
Multi-Action Support Bug

### ISSUE THREAD

**Issue by SENTINELITE** [SENTINELITE/StreamDeck-Shortcuts#5]
There's currently a bug, that's preventing Multi-Action support from working correctly.

Not sure when it broke, or why, but we'll be investigating it soon.

**Comment by SENTINELITE** [comment]
To update, I believe this is a bug with the underlying library. Hoping we can get this fixed, soon! 

See this issue: [emorydunn/StreamDeckPlugin#11](https://github.com/emorydunn/StreamDeckPlugin/issues/11)

**Comment by SENTINELITE** [comment]
Bug has been fixed & will release with the next release! 🎉

**Comment by danwkennedy** [comment]
@SENTINELITE is there an ETA for the next release? 🙂

**Comment by SENTINELITE** [comment]
Hey, @danwkennedy!

Sorry for the delay! I've been in between on other projects & just haven't circled back to this.  I wanted to release some more stuff in this patch, but I'll just fix this bug up.

I'll dig into it, & update it all, within this coming week.

Expect an to be released in ~7-14 days, depending on the verification checks!

**Comment by danwkennedy** [comment]
@SENTINELITE sounds good, thanks!

**Comment by danwkennedy** [comment]
Looks like that fixed it! Thanks so much @SENTINELITE . My Stream Deck just got way more useful 🙂

**Comment by SENTINELITE** [comment]
Awesome, @danwkennedy! Glad it'll fit into your workflow nicely!

Don't hesitate to reach out, if you think something else could use improvement!
