### ISSUE TITLE
Kilo-One

### ISSUE THREAD

**Issue by GENIODS** [SENTINELITE/StreamDeck-Shortcuts#8]
Hi, i have the problem "Kilo-One"

I send file log
[-1643899555025.log](https://github.com/SENTINELITE/StreamDeck-Shortcuts/files/7995537/-1643899555025.log)

Thank you

**Comment by SENTINELITE** [comment]
Hey, @GENIODS! Thanks for the log! This is a known issue. Please see issue: #2 

I'm going to go ahead & close this issue, as it's a duplicate. I'd advise you head over to that issue & subscribe for updates! 😄
