### ISSUE TITLE
the plugin does not show in Stream Deck Store

### ISSUE THREAD

**Issue by danicroitor** [SENTINELITE/StreamDeck-Shortcuts#9]
Just noticed that the plugin does not show in SD store and also when trying to install from the [website](https://apps.elgato.com/plugins/com.sentinelite.streamdeckshortcuts) I'm getting _The plugin “com.sentinelite.streamdeckshortcuts” is not available for download._

**Comment by SENTINELITE** [comment]
Hey, @danicroitor!

Can you try installing through the StreamDeck app? Maybe give the app a restart as well.

The website just deep links into the App's store. There shouldn't be an issue here, but the above steps should get you on the right path.

Let me know how that goes & if there's anything else I can help you with! 😊

**Comment by danicroitor** [comment]
Hi,
I haven’t tried to install it manually just directly from <https://apps.elgato.com/plugins/com.sentinelite.streamdeckshortcuts>. Tried multiple restart without success.
The app does not shows in stream deck app/plugin.

I'm trying to figure out how to download it manually and installing afterwards in stream deck app but no success so far.

**Comment by SENTINELITE** [comment]
@danicroitor That's strange…

Are you running on a Mac? What macOS are you on? Shortcuts is only available on 12.0+.

If all else fails, I'll attach the plug-in, you just won't get the automatic updates.

**Comment by danicroitor** [comment]
Did you received my last message. 
I running Mac OS 10.15.7

**Comment by SENTINELITE** [comment]
Hey, @danicroitor! 

I got your last message. Unfortunately, Apple only added Shortcuts to Mac with the most recent release of macOS 12.0, this past November. As such, there's no way to run this plugin on your device, until you update to macOS Monterey. 

I know that's not ideal, but that's the state of affairs.

**Comment by SENTINELITE** [comment]
I'm going to go ahead & close this issue as I haven't heard back from you, @danicroitor. If you're still having trouble, don't hesitate to re-open the issue! 😉

**Comment by vincenthavinh** [comment]
Hello, I encounter the same problem.
I have the stream deck XL, I use it with Windows 11.

I cannot find Shortcuts in the Stream Deck Store.

I can add details if you need more.

![no_shortcuts_app_in_store](https://user-images.githubusercontent.com/14567590/178901820-8d49aeb9-0aeb-41f4-ad00-52b7187d6f73.png)
.

**Comment by SENTINELITE** [comment]
Hey, @vincenthavinh! 

Unfortunately there's nothing that can be done. The plug-in is only for computers running macOS 12.0+.

This is because it's interacting with Apple-specific APIs that aren't available on Windows.

The only way I could ever see this being possible, is some sort of communication later between an iOS/Mac based device, that's in your possession & connected to the same local network. 

Even then, I'm not sure what the results would look like. 

Let me know if you have further questions, comments, or suggestions!
